require("tony.plugins-setup")

require("tony.core.options")
require("tony.core.keymaps")
require("tony.core.colorscheme")

require("tony.plugins.comment")
require("tony.plugins.nvim-tree")
require("tony.plugins.lualine")
require("tony.plugins.telescope")
require("tony.plugins.nvim-cmp")
require("tony.plugins.lsp.mason")
require("tony.plugins.lsp.lspsaga")
require("tony.plugins.lsp.lspconfig")
require("tony.plugins.lsp.null-ls")
require("tony.plugins.autopairs")
require("tony.plugins.treesitter")
require("tony.plugins.gitsigns")
require("tony.plugins.colorizer")
require("tony.plugins.bufferline")
require("tony.plugins.omnisharp")
require("tony.plugins.ale")
require("tony.plugins.bracey")
-- require("tony.plugins.indent_blankline")
require("tony.plugins.flutter-tools")
